name: Lint Project

on:
  workflow_call:
  workflow_dispatch:

permissions: {}

jobs:
  lint-project:
    name: Lint Project
    runs-on: ubuntu-26.04-arm
    timeout-minutes: 5
    concurrency:
      group: lint-project-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Setup Environment
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
        with:
          version: 2026.6.13
          install_args: bun

      - name: Install Dependencies
        run: bun ci

      - name: Check Formatting
        run: bun format --check

      - name: Lint & Type check
        run: bun lint --deny-warnings
