name: Lint Actions

on:
  workflow_call:
  workflow_dispatch:

permissions: {}

jobs:
  lint-actions:
    name: Lint Actions
    runs-on: ubuntu-26.04-arm
    timeout-minutes: 5
    permissions:
      security-events: write # Required for upload-sarif to upload SARIF files.
    concurrency:
      group: lint-actions-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Setup Environment
        uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925 # v4.1.0
        with:
          version: 2026.6.10
          install_args: zizmor actionlint shellcheck

      - name: Run zizmor 🌈
        run: |
          zizmor . --pedantic --color=always --format=sarif > zizmor.sarif
        env:
          ZIZMOR_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run actionlint
        continue-on-error: true
        run: |
          actionlint -format "$(cat .github/actionlint-sarif.txt)" -color -ignore 'label "ubuntu-26\.04-arm" is unknown' > actionlint.sarif

      - name: Upload zizmor SARIF file
        uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
        with:
          sarif_file: zizmor.sarif
          category: zizmor

      - name: Upload actionlint SARIF file
        uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
        with:
          sarif_file: actionlint.sarif
          category: actionlint
